services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: materiappdb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev"] #--import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 123456
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      #- /home/christian/Documentos/udenar/desarrolloWeb/project_end/api-materiapp/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./src/modules/auth/keycloak/themes/materiapp:/opt/keycloak/themes/materiapp
    depends_on:
      - postgres
 
volumes:
  postgres-data: